// Resumable state for the explanation pipeline.
//
// explain_state.<projectRef>.json is the machine source of truth;
// EXPLAIN_PROGRESS.<projectRef>.md is regenerated from it after EVERY test so an
// interruption at any point still leaves an accurate human-readable summary
// behind. Every path here is target-keyed, so setTarget() must be called before
// any of these functions - generate.mjs does it as its first act.
//
// Granularity is one entry per TEST, written only once that test's rows are
// committed to the DB. A crash mid-test replays that test; because writes are
// keyed by row id and skip anything already populated, a replay cannot
// duplicate or double-write.

import { readFileSync, writeFileSync, existsSync, renameSync, mkdirSync } from 'node:fs';

const DIR = new URL('./', import.meta.url);

// State, logs and the progress table are ALL per target project.
//
// This is not tidiness. 24 of dev's reading tests share their UUID with prod, so
// a single state file keyed by test id would mark those tests "done" from the
// dev run and silently skip them when the same script is pointed at prod -
// leaving 291 prod questions unexplained while reporting success.
let target = 'unknown';
export function setTarget(ref) {
  target = ref || 'unknown';
}

const p = (name, ext) => new URL(`./${name}.${target}.${ext}`, import.meta.url);
const statePath = () => p('explain_state', 'json');
const logPath = () => p('generated_log', 'jsonl');
const flagPath = () => p('flagged', 'jsonl');
const MD_PATH = () => new URL(`../../EXPLAIN_PROGRESS.${target}.md`, import.meta.url);

export function loadState() {
  if (!existsSync(statePath())) return null;
  return JSON.parse(readFileSync(statePath(), 'utf8'));
}

function writeJsonAtomic(path, obj) {
  const tmp = new URL(path.href + '.tmp');
  writeFileSync(tmp, JSON.stringify(obj, null, 2));
  renameSync(tmp, path);
}

export function newState({ model, target }) {
  const prev = loadState();
  return {
    version: 1,
    model,
    target,
    createdAt: prev?.createdAt ?? new Date().toISOString(),
    updatedAt: null,
    entries: prev?.entries ?? {},
  };
}

export function saveState(state) {
  state.updatedAt = new Date().toISOString();
  writeJsonAtomic(statePath(), state);
  writeFileSync(MD_PATH(), renderMarkdown(state));
}

/** Append-only audit trail: every explanation produced, and every flag raised. */
export function appendLog(records) {
  if (!records.length) return;
  mkdirSync(new URL('./', DIR), { recursive: true });
  writeFileSync(logPath(), records.map((r) => JSON.stringify(r)).join('\n') + '\n', { flag: 'a' });
}

export function appendFlags(records) {
  if (!records.length) return;
  writeFileSync(flagPath(), records.map((r) => JSON.stringify(r)).join('\n') + '\n', { flag: 'a' });
}

/** Row ids this pipeline has already written, read back from the audit log. */
export function priorRunRowIds() {
  if (!existsSync(logPath())) return new Set();
  const ids = new Set();
  for (const line of readFileSync(logPath(), 'utf8').split('\n')) {
    if (!line.trim()) continue;
    try { ids.add(JSON.parse(line).rowId); } catch { /* skip a torn final line */ }
  }
  return ids;
}

export function summarize(state) {
  const all = Object.values(state.entries);
  const sum = (k) => all.reduce((n, e) => n + (e[k] ?? 0), 0);
  return {
    tests: all.length,
    done: all.filter((e) => e.status === 'done').length,
    failed: all.filter((e) => e.status === 'failed').length,
    generated: sum('generated'),
    skippedHandAuthored: sum('skippedHandAuthored'),
    skippedPriorRun: sum('skippedPriorRun'),
    flagged: sum('flagged'),
  };
}

function renderMarkdown(state) {
  const s = summarize(state);
  const rows = Object.values(state.entries).sort((a, b) =>
    a.title.localeCompare(b.title, undefined, { numeric: true })
  );
  const ICON = { done: '✅', failed: '❌', partial: '⚠️' };

  const lines = [
    '# Reading Explanation Progress',
    '',
    '<!-- Generated by scripts/explain/. Do not hand-edit: rewritten after every test. -->',
    '',
    `**Last updated:** ${state.updatedAt ?? 'never'}  `,
    `**Model:** \`${state.model}\`  `,
    `**Target project:** \`${state.target}\`  `,
    `**Target column:** \`questions.explanation\` (reading only)`,
    '',
    '## Summary',
    '',
    '| | Count |',
    '|---|---|',
    `| tests completed | ${s.done} |`,
    `| tests failed | ${s.failed} |`,
    `| **explanations generated** | **${s.generated}** |`,
    `| skipped — hand-authored, preserved | ${s.skippedHandAuthored} |`,
    `| skipped — written by an earlier run | ${s.skippedPriorRun} |`,
    `| flagged (not explained) | ${s.flagged} |`,
    '',
    '## Tests',
    '',
    '| | Test | Questions | Generated | Hand-authored kept | Prior run | Flagged | Last run | Note |',
    '|---|---|---|---|---|---|---|---|---|',
  ];

  for (const e of rows) {
    lines.push(
      `| ${ICON[e.status] ?? '?'} | ${e.title} | ${e.questions ?? '?'} | ${e.generated ?? 0} | ` +
        `${e.skippedHandAuthored ?? 0} | ${e.skippedPriorRun ?? 0} | ${e.flagged ?? 0} | ` +
        `${e.lastRunAt?.replace('T', ' ').slice(0, 19) ?? '—'} | ` +
        `${(e.error ?? '').replace(/\|/g, '\\|').slice(0, 70)} |`
    );
  }

  lines.push(
    '',
    '## Artefacts',
    '',
    `- \`scripts/explain/generated_log.${target}.jsonl\` — every explanation produced (test, question, output)`,
    `- \`scripts/explain/flagged.${target}.jsonl\` — every question flagged instead of explained`,
    '',
    '## Resuming',
    '',
    '```bash',
    'cd platform',
    'node --env-file=.env.explain scripts/explain/generate.mjs           # continue',
    'node --env-file=.env.explain scripts/explain/generate.mjs --status  # report only',
    '```',
    '',
    'Completed tests are skipped. Questions that already have an explanation are never',
    'overwritten, so a replay is always safe.',
    ''
  );

  return lines.join('\n');
}
