// Resumable state for the transcription pipeline.
//
// transcription_state.json is the machine source of truth; TRANSCRIPTION_PROGRESS.md
// is regenerated from it after EVERY mutation so an interruption at any point
// still leaves an accurate human-readable summary behind.

import { readFileSync, writeFileSync, existsSync, renameSync } from 'node:fs';
import { fmtDuration } from './lib.mjs';

const STATE_PATH = new URL('./transcription_state.json', import.meta.url);
const MD_PATH = new URL('../../TRANSCRIPTION_PROGRESS.md', import.meta.url);

export const STATUSES = ['pending', 'in_progress', 'done', 'failed', 'blocked'];

export function loadState() {
  if (!existsSync(STATE_PATH)) return null;
  return JSON.parse(readFileSync(STATE_PATH, 'utf8'));
}

/** Atomic write: temp file + rename, so a crash mid-write cannot truncate state. */
function writeJsonAtomic(path, obj) {
  const tmp = new URL(path.href + '.tmp');
  writeFileSync(tmp, JSON.stringify(obj, null, 2));
  renameSync(tmp, path);
}

export function saveState(state) {
  state.updatedAt = new Date().toISOString();
  writeJsonAtomic(STATE_PATH, state);
  writeFileSync(MD_PATH, renderMarkdown(state));
}

/** Build initial state from the inventory dump. Preserves any existing progress. */
export function buildState(inventory, model) {
  const prev = loadState();
  const entries = {};

  for (const t of inventory.tests) {
    const audioPart = [...t.parts]
      .sort((a, b) => a.part_number - b.part_number)
      .find((p) => p.listening_url);
    const audioRow = audioPart
      ? inventory.audio.find((a) => a.url === audioPart.listening_url)
      : null;

    const existing = prev?.entries?.[t.id];
    entries[t.id] = {
      testId: t.id,
      title: t.title,
      audioUrl: audioPart?.listening_url ?? null,
      audioPartId: audioPart?.id ?? null,
      audioPartNumber: audioPart?.part_number ?? null,
      partNumbers: t.parts.map((p) => p.part_number).sort((a, b) => a - b),
      durationSec: audioRow?.durationSec ?? null,
      bytes: audioRow?.bytes ?? null,
      // Preserve prior progress; tests with no audio can never be transcribed.
      status: existing?.status ?? (audioPart ? 'pending' : 'blocked'),
      lastAttemptAt: existing?.lastAttemptAt ?? null,
      attempts: existing?.attempts ?? 0,
      error: existing?.error ?? (audioPart ? null : 'No listening_url on any part row'),
      transcriptChars: existing?.transcriptChars ?? null,
      partsWritten: existing?.partsWritten ?? null,
      splitOk: existing?.splitOk ?? null,
      tokensIn: existing?.tokensIn ?? null,
      tokensOut: existing?.tokensOut ?? null,
    };
  }

  return { version: 1, model, createdAt: prev?.createdAt ?? new Date().toISOString(), updatedAt: null, entries };
}

export function summarize(state) {
  const all = Object.values(state.entries);
  const by = (s) => all.filter((e) => e.status === s).length;
  return {
    total: all.length,
    done: by('done'),
    pending: by('pending'),
    failed: by('failed'),
    in_progress: by('in_progress'),
    blocked: by('blocked'),
    remainingSec: all
      .filter((e) => ['pending', 'failed', 'in_progress'].includes(e.status))
      .reduce((n, e) => n + (e.durationSec ?? 0), 0),
  };
}

/** Work queue: anything not done and not blocked, including stuck in_progress. */
export function workQueue(state) {
  return Object.values(state.entries)
    .filter((e) => ['pending', 'failed', 'in_progress'].includes(e.status))
    .sort((a, b) => a.title.localeCompare(b.title, undefined, { numeric: true }));
}

const ICON = { done: '✅', pending: '⬜', failed: '❌', in_progress: '🔄', blocked: '🚫' };

function renderMarkdown(state) {
  const s = summarize(state);
  const rows = Object.values(state.entries).sort((a, b) =>
    a.title.localeCompare(b.title, undefined, { numeric: true })
  );
  const pct = s.total ? Math.round((s.done / (s.total - s.blocked || 1)) * 100) : 0;

  const lines = [
    '# Listening Transcription Progress',
    '',
    '<!-- Generated by scripts/transcribe/. Do not hand-edit: rewritten after every file. -->',
    '',
    `**Last updated:** ${state.updatedAt ?? 'never'}  `,
    `**Model:** \`${state.model}\`  `,
    `**Target:** \`part.content\`, one transcript slice per part row`,
    '',
    '## Summary',
    '',
    `| Status | Count |`,
    `|---|---|`,
    `| ✅ done | ${s.done} |`,
    `| ⬜ pending | ${s.pending} |`,
    `| 🔄 in_progress (stuck) | ${s.in_progress} |`,
    `| ❌ failed | ${s.failed} |`,
    `| 🚫 blocked (no audio) | ${s.blocked} |`,
    `| **total** | **${s.total}** |`,
    '',
    `**Transcribable:** ${s.total - s.blocked} · **complete:** ${s.done} (${pct}%) · ` +
      `**audio left:** ${fmtDuration(s.remainingSec)} (${(s.remainingSec / 3600).toFixed(1)} h, ` +
      `~${Math.round((s.remainingSec * 32) / 1000).toLocaleString()}k input tokens)`,
    '',
    '## Files',
    '',
    '| | Test | Part rows | Audio on | Duration | Status | Attempts | Last attempt | Split | Note |',
    '|---|---|---|---|---|---|---|---|---|---|',
  ];

  for (const e of rows) {
    const note = e.error ? e.error.replace(/\|/g, '\\|').slice(0, 90) : '';
    const split = e.status === 'done' ? (e.splitOk ? `4 parts` : `⚠ ${e.partsWritten ?? '?'} part(s)`) : '';
    lines.push(
      `| ${ICON[e.status] ?? '?'} | ${e.title} | ${e.partNumbers.join(',')} | ` +
        `${e.audioPartNumber ?? '—'} | ${fmtDuration(e.durationSec)} | ${e.status} | ` +
        `${e.attempts} | ${e.lastAttemptAt ? e.lastAttemptAt.replace('T', ' ').slice(0, 19) : '—'} | ` +
        `${split} | ${note} |`
    );
  }

  lines.push(
    '',
    '## Resuming',
    '',
    '```bash',
    'cd platform',
    'node --env-file=.env.transcribe scripts/transcribe/transcribe.mjs          # continue',
    'node --env-file=.env.transcribe scripts/transcribe/transcribe.mjs --status # report only',
    '```',
    '',
    'Skips `done`. Retries `failed` and stuck `in_progress`. `blocked` rows have no audio in the DB',
    'and need a `listening_url` before they can be transcribed.',
    ''
  );

  return lines.join('\n');
}
