// Resumable state for the ingestion pipeline.
//
// Same shape as scripts/explain/state.mjs and scripts/transcribe/state.mjs:
// ingest_state.<projectRef>.json is the machine source of truth and
// INGEST_PROGRESS.<projectRef>.md is regenerated from it after every mutation, so
// an interruption still leaves an accurate human-readable summary behind.
//
// Paths are keyed by target project. That is not tidiness: dev and prod share test
// UUIDs, so one shared file would let a dev run mark a job done and a prod run skip
// it. setTarget() must be called before anything else here.

import { readFileSync, writeFileSync, existsSync, renameSync } from 'node:fs';

let target = 'unknown';
export function setTarget(ref) {
  target = ref || 'unknown';
}

const statePath = () => new URL(`./ingest_state.${target}.json`, import.meta.url);
const mdPath = () => new URL(`../../INGEST_PROGRESS.${target}.md`, import.meta.url);

export function loadState() {
  if (!existsSync(statePath())) return { version: 1, updatedAt: null, jobs: {} };
  return JSON.parse(readFileSync(statePath(), 'utf8'));
}

function writeJsonAtomic(path, obj) {
  const tmp = new URL(path.href + '.tmp');
  writeFileSync(tmp, JSON.stringify(obj, null, 2));
  renameSync(tmp, path);
}

export function saveState(state) {
  state.updatedAt = new Date().toISOString();
  writeJsonAtomic(statePath(), state);
  writeFileSync(mdPath(), renderMarkdown(state));
}

/**
 * Record a stage outcome for a job. Stages run parse -> validate -> apply; a job
 * that has reached 'applied' is never re-applied, so a replay cannot double-write
 * a test.
 */
export function recordStage(state, jobId, stage, detail = {}) {
  const job = state.jobs[jobId] ?? { jobId, createdAt: new Date().toISOString(), stages: {} };
  job.stages[stage] = { at: new Date().toISOString(), ...detail };
  job.status = stage;
  state.jobs[jobId] = job;
  saveState(state);
  return job;
}

export function jobStatus(state, jobId) {
  return state.jobs[jobId]?.status ?? null;
}

export function summarize(state) {
  const jobs = Object.values(state.jobs);
  return {
    jobs: jobs.length,
    applied: jobs.filter((j) => j.status === 'applied').length,
    validated: jobs.filter((j) => j.status === 'validated').length,
    parsed: jobs.filter((j) => j.status === 'parsed').length,
    failed: jobs.filter((j) => j.status === 'failed').length,
  };
}

function renderMarkdown(state) {
  const s = summarize(state);
  const rows = Object.values(state.jobs).sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));
  const ICON = { applied: '✅', validated: '🔍', parsed: '📄', failed: '❌' };

  const lines = [
    '# Content Ingestion Progress',
    '',
    '<!-- Generated by scripts/ingest/. Do not hand-edit: rewritten after every stage. -->',
    '',
    `**Last updated:** ${state.updatedAt ?? 'never'}  `,
    `**Target project:** \`${target}\`  `,
    '',
    '## Summary',
    '',
    '| | Count |',
    '|---|---|',
    `| jobs | ${s.jobs} |`,
    `| **written to the database** | **${s.applied}** |`,
    `| validated, awaiting apply | ${s.validated} |`,
    `| parsed only | ${s.parsed} |`,
    `| failed | ${s.failed} |`,
    '',
    '## Jobs',
    '',
    '| | Job | Test | Type | Questions | Stage | Last run |',
    '|---|---|---|---|---|---|---|',
  ];

  for (const j of rows) {
    const a = j.stages.applied ?? j.stages.validated ?? j.stages.parsed ?? {};
    lines.push(
      `| ${ICON[j.status] ?? '?'} | ${j.jobId} | ${(a.title ?? '—').slice(0, 40)} | ${a.testType ?? '—'} | ` +
        `${a.questions ?? '—'} | ${j.status ?? '—'} | ${(j.stages[j.status]?.at ?? '').replace('T', ' ').slice(0, 19)} |`
    );
  }

  lines.push(
    '',
    '## Resuming',
    '',
    '```bash',
    'cd platform',
    'node --env-file=.env.ingest scripts/ingest/ingest.mjs --status',
    'node --env-file=.env.ingest scripts/ingest/ingest.mjs <folder>          # parse + validate',
    'node --env-file=.env.ingest scripts/ingest/ingest.mjs <folder> --apply  # write',
    '```',
    '',
    'A job that reached `applied` is never re-applied. Delete its entry to force a re-run.',
    ''
  );

  return lines.join('\n');
}
